### ISSUE TITLE
Can this already be tested?

### ISSUE THREAD

**Issue by ltorrespr** [jeremySchriver/Forza_telemetry_project#1] opened 2024-02-16 02:34 UTC
Hi Jeremy!

I was wondering if your project is in a state where one can perform some initial evaluations. If so, please let me know what instructions to follow to build/test.  Thank you!

**Comment by jeremySchriver** [comment] 2024-02-16 20:47
Let me see what I can come up with tonight to have a build that is partially usable while I continue to build modules.
As it stands now the telemetryCapture.py file, within the develop branch, can be run via terminal to capture dash information into a csv file for later ingestion. If attempting to run this please do update your file paths for output and note that writing to CSV only occurs while active in a race .

However I will look to merge some of the recent dev work into a stable master build for you tonight so you can at least use the capture functionality without much issue.

Out of curiosity, other than capturing the packets, what functionalities are you looking for in an app like this? My goal started out as just syncing case lights to the tachometer but quickly learned it is much more complex of an equation to set optimal shift points. As such telemetry capture and rolling road data seemed like a solid next step.

**Comment by ltorrespr** [comment] 2024-02-16 21:27
Thank you! Will try a couple of things.

As far as functionality, there are a number of items that I am interested in. For example, over time one can develop Dyno graphs from the data (HP & Torque vs rpm or vs speed), average speed per track per car, etc... Yet, as a start, just having the data available and visible to be able to graph various things would be great.

Again, thank you for your development work!

**Comment by jeremySchriver** [comment] 2024-02-16 21:41
Interesting I hadn't thought about capturing any over time analytics per course, I will add that to my backlog of thoughts for additional modules. I will be sure to focus on the Dyno features like you suggested though.

I did recently add some pieces in that attempt to fill/normalize the data I was capturing, via the csvFiller file, but this is still very much in the works.
![image](https://github.com/jeremySchriver/Forza_telemetry_project/assets/157846828/4bd57238-89cb-4f78-a797-ec1f96eee735)

The data I captured was for one lap in an Acura NSX with 9 gears so there were so many gaps in the data it made the scatter plot near unusable. Let me focus on these pieces tonight so you can help build some sample data for me to improve the normalization functions.

**Comment by ltorrespr** [comment] 2024-02-16 23:43
Here is something I created in Excel for a Dyno chart for the '65 Mustang....

<img width="1371" alt="Screenshot 2024-02-16 at 3 39 39 PM" src="https://github.com/jeremySchriver/Forza_telemetry_project/assets/4351230/ff1800a0-5fa8-4d9f-aea9-8e624d058f55">


Basically, I took a video while driving with Telemetry displaying, then, played the vid back in "slomo" and stopped to grab the data (rpm, mph, Torque, and HP at the moment), then, put the data into the spreadsheet and graphed the data. Somewhat cumbersome process.  Which I hope can be automated with the work that many of you guys are doing.

Thanks!

**Comment by ltorrespr** [comment] 2024-02-16 23:47
Another thought....just brainstorming here.... with the new settings of Ride Center Height Offsets (RCHOs) and Anti-Geometry Percentages (AGPs), would be good to analyze the impact they have on turning ability by maybe going in a circle and seeing which deliver the smallest to largest circle!!! A combo of this with Springs, B&R, and ARBs. OK, I better stop myself!...lol....

**Comment by ltorrespr** [comment] 2024-02-17 03:44
Jeremy - while trying to run telemetryCapture.py, I got the following error: 

/Forza-Telemetry/Forza_telemetry_project-main_Jeremy/telemetryCapture.py", line 3, in <module>
    from openrgb import OpenRGBClient
ModuleNotFoundError: No module named 'openrgb'

It appears I am missing a file (or more) from the zip file I downloaded of you code. Please let me know.  I already changed to the correct file output and location.

Files in Dir....

<img width="457" alt="Screenshot 2024-02-16 at 7 45 09 PM" src="https://github.com/jeremySchriver/Forza_telemetry_project/assets/4351230/c86ac90b-4d34-4e6c-84f2-a5797d0ead8d">



Thanks!

**Comment by ltorrespr** [comment] 2024-02-17 07:07
Figured that one out, so,  installed openrgb-python.
Now some issues with led_conditions (line 5)

Traceback (most recent call last):
  File "/Forza-Telemetry/Forza_telemetry_project-main_Jeremy/telemetryCapture.py", line 8, in <module>
    import led_conditions
  File "/Forza-Telemetry/Forza_telemetry_project-main_Jeremy/led_conditions.py", line 5
    match condition:
          ^
SyntaxError: invalid syntax

Will keep trying to debug.

**Comment by ltorrespr** [comment] 2024-02-17 07:26
Success! Got it to work with the following changes....(on file led_conditions.py), at least this particular hurdle. Still to get actual data.


BTW, after I run "python telemetryCapture.py", how do I stop the capturing of data (on my Mac terminal)?


<img width="332" alt="Screenshot 2024-02-16 at 11 27 26 PM" src="https://github.com/jeremySchriver/Forza_telemetry_project/assets/4351230/b669c65a-f15d-4b9f-8cca-a684254fec0d">


Tomorrow I will keep debugging, and, also try to debug some more of the files provided by Austin.

Luis

**Comment by jeremySchriver** [comment] 2024-02-17 13:20
Going to go ahead and close this bug out as a new version of the master branch has been published.
The last issue you were having was caused by my lazy, copypasta, of my initial testing of the openRBG sdk. In the new version of telemetryCapture I have removed all unnecessary libraries and cleaned/commented the code a bit more. It should now run without issues for you assuming the game is already running.

To cancel the loop started by this script go into your terminal window and perform a keyboard interrupt. For Windows this is done by pressing "crtl+c" and it looks like for Mac it is "Cmd + Shift + C".

Next iteration will look to add a GUI to this script to allow for a start and stop button.

**Closed as completed by jeremySchriver** 2024-02-17 13:20 UTC

**Comment by ltorrespr** [comment] 2024-02-17 19:01
Your new code is working just fine here! GREAT job Jeremy. I was able to get data back once I changed the ip on the sniffer.py & telemetryCapture.py.

Quick questions:

  1.  Within color_setter.py, there are many lines with "client = OpenRGBClient('127.0.0.1', 6742, 'My client!')", does this particular ip stay as-is? Just curious what it represents. I left it w/o change.
  2. There is a file named "telemtryFiller.py", is this a misnamed file? Should it actually be "telemetryFiller.py"?


BTW, Keyboard Interrupt for Mac is also "control + c".

Thank you!

Luis
________________________________
